version: '3.7'
services:
  customer-api:
    build:
      context: ./customer-api
    container_name: customer-api
    ports:
    - "8081:8080"

  products-api:
    build:
      context: ./products-api
    container_name: products-api
    ports:
      - "8082:8080"

  sales-api:
    build:
      context: ./sales-api
    container_name: sales-api
    ports:
      - "8083:8080"
